version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
  release:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
      - run: git config --global user.name "$GIT_AUTHOR_NAME"
      - run: yarn run release
  deploy_prod:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run:
          name: Deploy SLS
          command: |
            yarn sls
workflows:
  do_build:
    jobs:
      - test:
          context: epm_web_prod
          filters:
            branches:
              ignore:
                - dev
                - stage
                - master
      - release:
          context: private_packages
          filters:
            branches:
              only:
                - dev
                - stage
                - master
      - deploy_prod:
          context: epm_web_prod
          filters:
            branches:
              only:
                - master
